### ISSUE TITLE
Allow copy / pasting of errors when debugging?

### ISSUE THREAD

**Issue by Ashe** [s-clerc/slyblime#5]
If I get an error in the REPL, I get it all in the terminal and it can be easily copied and pasted (I'm a beginner so I tend to be copying and pasting my errors when I'm receiving help). I love your interactive debugging process and it's amazing! But I do think a dump of the error how it would be presented in the REPL at the bottom of the page would be useful just when you do want to copy and paste?

If there is a way to copy and paste it, maybe it needs to be explained on the readme for new users? :) Thank you!

**Comment by s-clerc** [comment]
Hi! Thanks for using my plugin.

Yeah, I was actually having the same issue yesterday while trying to share error messages with the discord. The reason you couldn't copy/paste is that it wasn't implemented by the ST devs — I was under the false impression they would, which is why I hadn't really bothered before. I've now added two buttons to facilitate copying in c29ba9ee3d3319069998fa6d5ff6c3adbddabe2d:

<img width="768" alt="image" src="https://user-images.githubusercontent.com/2052887/93527489-3c662280-f939-11ea-871b-9e684fcf7c24.png">

`Copy condition` copies the condition description and restarts and `Copy all` includes the backtrace, here's a sample:
```lisp
Unbound variable: AOEU
   [Condition of type UNBOUND-VARIABLE] in thread 400
Restarts:
	【0】CONTINUE: Retry getting the value of AOEU.
	【1】USE-VALUE: Specify a value of AOEU to use this time.
	【2】STORE-VALUE: Specify a value of AOEU to store and use.
	【3】RETRY: Retry SLY mREPL evaluation request.
	【4】*ABORT: Return to SLY's top level.
	【5】ABORT-BREAK: Reset this thread
	【6】ABORT: Kill this thread
```

This addition is available in [Aiguillions](https://github.com/s-clerc/slyblime/releases/tag/0.2.0) and it should be available on Package Control in a bit (tbh I'm not sure quite how long it takes). Alternatively, you can download the source and copy it to the packages folder.

Thanks for your feedback! Don't hesitate to ask any more questions or leave any more comments ☺️

**Comment by Ashe** [comment]
This looks perfect! Thank you so much! I'll test it out after work today! Loving this so far, makes common lisp development so much more fun! :)
